#!/bin/sh 

#turn off auto expansion
set -f

. alterator-sh-functions

on_message()
{
	case "$in_action" in
		#information for renderer
		template)
			if [ "$in__objects" = "/" ];then
				echo '('
				echo 'template "card-index" '
				echo 'url "net-eth.html"'
				echo ')'
			else
				echo '#f'
			fi
			;;
		*)
			echo '#f'
	esac
}

message_loop
