#!/bin/sh -e

len=$1;shift
position=$((0xFFFFFFFF))

[ "$len" -ge 0 -a "$len" -le 32 ] 2>/dev/null
mask=$(( $position - ($position >> $len) ))

printf '%s.%s.%s.%s\n' \
    "$(($mask >> 24 & 0xff))" \
    "$(($mask >> 16 & 0xff))" \
    "$(($mask >> 8 & 0xff))" \
    "$(($mask & 0xff))"
