#!/bin/sh

################### shell file helpers

ifdumptool="/etc/net/scripts/contrib/ifdump"

. /etc/net/scripts/functions

shell_add_or_subst()
{
	local name="$1" && shift
	local value="$1" && shift
	local file="$1" && shift

	[ -f "$file" ] || touch "$file"
	if grep -qs "^$name" "$file"; then
		/bin/sed -r -i "s,^$name.*,$name$value," -- "$file"
		return 0
	fi
	printf %s\\n "$name$value" >> "$file"
}

shell_get()
{
	local name="$1" && shift
	local file="$1" && shift

	[ -f "$file" ] &&
	grep -qs "^$name=" "$file" &&
	grep "^$name=" "$file"|sed "s,^$name=,,"
}

################### interface modificators

list_iface()
{
	echo "("
	/sbin/ip link|egrep '^[[:digit:]]+'|
		sed -r 's,^[[:digit:]]+\:[[:space:]]+([^:]+).*,\1,'|
		grep 'eth0'|
                sed 's,.*,("&"),'
	echo ")"
}

read_iface()
{
	echo "("
	local name="$1" && shift
	addr=$(grep '^[0-9]' "/etc/net/ifaces/$name/ipv4address" | head -n1 || echo "")
	ip="${addr%%/*}"
	mask="${addr#$ip}"; mask="${mask#/}"
	printf 'ip "%s" mask "%s"\n' "$ip" "$mask"
	printf 'default "%s"\n' \
		$(grep '^default' "/etc/net/ifaces/$name/ipv4route" | sed -r 's,default[[:space:]]+via[[:space:]],,' || echo "")

	(eval $("$ifdumptool" "$name")
		[ "$BOOTPROTO" = "dhcp" ] && echo "dhcp #t" || echo "dhcp #f"
		is_yes "$DISABLED" && echo "state #f" || echo "state #t")
		
	echo ")"
}

write_iface()
{
	local name="$1" && shift
	[ -d "/etc/net/ifaces/$name" ] || mkdir "/etc/net/ifaces/$name"
	[ -n "$in_mask" ] && [ -n "$in_ip" ] && \
		printf '%s/%s\n' "$in_ip" "$in_mask" >"/etc/net/ifaces/$name/ipv4address"
	[ -n "$in_default" ] &&
		printf 'default via %s\n' "$in_default" >"/etc/net/ifaces/$name/ipv4route"
	tmpfile=$(mktemp "/etc/net/ifaces/$name/options.XXXXXX")
	cat "/etc/net/ifaces/$name/options" >"$tmpfile" 
	[ -n "$in_dhcp" ] &&
		shell_add_or_subst "BOOTPROTO=" \
			$([ "$in_dhcp" = "#t" ] && echo "dhcp" || echo "static")\
			"$tmpfile"
	[ -n "$in_state" ] &&
		shell_add_or_subst "DISABLED=" \
			$([ "$in_state" = "#t" ] && echo "no" || echo "yes") \
			"$tmpfile"
	/sbin/service network stop >&2 &&
	mv -f "$tmpfile" "/etc/net/ifaces/$name/options" &&
	/sbin/service network start >&2
}


. /usr/share/alterator/build/backend3.sh

on_message()
{
	case "$in_action" in
		list)
			list_iface
			;;
		read) 
			read_iface "$in__objects"
			;;
		write)
			write_iface "$in__objects"
			echo "()"
			;;
	esac
}

message_loop

