#!/bin/sh 

_()
{
LANG=${in_language%%;*}.utf8 gettext "alterator-net-tcp" "$1"
}

#turn off auto expansion
set -f

. /usr/share/alterator/build/backend3.sh

on_message()
{
	case "$in_action" in
		#information for renderer
		template)
			if [ "$in__objects" = "/" ];then
				echo '('
				echo 'template "card-index" '
				echo 'url "net-tcp.html"'
				echo ')'
			else
				echo '#f'
			fi
			;;
		info)
			echo '('
			printf ' title "%s"' "$(_ "IP interfaces")"
			printf ' description "%s"' "$(_ "IP interfaces administration")"
			printf ' group "%s"' "$(_ "Network")"
			echo ')'
			;;
		*)
			echo '#f'
	esac
}


message_loop

