#!/bin/sh 

_()
{
LANG=${in_language%%;*}.utf8 gettext "alterator-net-tcp" "$1"
}

#turn off auto expansion
set -f

. /usr/share/alterator/build/backend3.sh

on_message()
{
	case "$in_action" in
		#information for renderer
		template)
			if [ "$in__objects" = "/" ];then
				echo '('
				echo 'template "card-index" '
				echo 'url "/var/www/html/fbi/net-tcp.html"'
				echo ')'
			else
				echo '#f'
			fi
			;;
		info)
			echo '('
			printf ' title "%s"' "$(_ "TCP/IP Connections")"
			printf ' description "%s"' "$(_ "TCP/IP connections administration")"
			echo ')'
			;;
		*)
			echo '#f'
	esac
}


message_loop

