#!/bin/sh 

#turn off auto expansion
set -f

. /usr/share/alterator/build/backend3.sh

on_message()
{
	case "$in_action" in
		#information for renderer
		template)
			if [ "$in__objects" = "/" ];then
				echo '('
				echo 'template "card-index" '
				echo 'url "/var/www/html/fbi/net-tcp.html"'
				echo ')'
			else
				echo '#f'
			fi
			;;
		*)
			echo '#f'
	esac
}


message_loop

